### ISSUE TITLE
SelectedColor binding doesn't get updated

### ISSUE THREAD

**Issue by Sennevds** [vpapenko/ColorPicker#29]
I'm trying to use this nuget package but I've got a problem with the ColorWheel.
When the initial value of the SelectedColor is black(Color.FromHex("#FF000000")) and I use the the colorpicker to set a new value my property in the viewmodel isn't updated.
When I first set my property to another color and then update via the colorwheel my setter is triggerd
Viewmodel property:
```C#
   public Color EditedColor1
        {
            get { return _editedColor1; }
            set
            {
                _editedColor1 = value;
                Settings.AddOrUpdateValue("color1", _editedColor1.ToHex());
                RaisePropertyChanged(() => EditedColor1);
                ColorChanged(1);
            }
        }
```
View
```xaml
<colorPicker1:ColorWheel Grid.Row="2" Grid.Column="0" x:Name="ColorWheel1" VerticalOptions="FillAndExpand"
                                    ShowAlphaSlider="False"
                                    ShowLuminositySlider="False"
                                    ShowLuminosityWheel="False" SelectedColor="{Binding EditedColor1, Mode=TwoWay}" PropertyChanged="ColorWheel1_OnPropertyChanged"
                                    />
```
I didn't use the nuget package itself because I'm using a newer version of Xamarin forms so I downloaded your code updated the package and used that dll.

With the slides the problem doesn't occur.

**Comment by vpapenko** [comment]
Hi.
You set black as initial color and use only color circle.
Color circle affects Hue and Saturation, but with Luminosity = 0 (from initial black color) you always end up with black color.
If you want to get a saturated color, as you can see in the color circle, you need Luminosity = 0.5. May be gray initial color is what you need? If I understand your problem correctly.
P.S. I will update Nuget dependencies and publish new version.

**Comment by Sennevds** [comment]
Okay that seems the problem indeed but maybe you need to change the default value for SelectedColorProperty because if someone will use only your colorpicker and no sliders it wont work
```
public static readonly BindableProperty SelectedColorProperty = BindableProperty.Create(
           nameof(SelectedColor),
           typeof(Color),
           typeof(IColorPicker),
           Color.Black,
           propertyChanged: new BindableProperty.BindingPropertyChangedDelegate(HandleSelectedColorSet), defaultBindingMode: BindingMode.TwoWay);
```
And thanks for the control it works really nice!

**Comment by vpapenko** [comment]
Good idea.
I published a new version with the latest Xamarin Forms and gray as default color.
Thank you for your feedback.
