### ISSUE TITLE
NetStandard.Library 2.1 required, latest version is 2.0.3

### ISSUE THREAD

**Issue by BloodyRain2k** [vpapenko/ColorPicker#32]
When I try to install this package through NuGet, it fails with the complaint that it's not compatible with NetStandard.Library 2.0 and that I need 2.1

The only issue is that there's no 2.1 NetStandard.Library available to me.
I'm on the latest release of that package and that's 2.0.3

Here's a screen showing that I can't update my version any higher
https://drive.google.com/open?id=15WOeztPKYt-MfhZPLIhBc_3YUrGJekkZ

and here's the package requiring 2.1
https://drive.google.com/open?id=1UVytQ7jorgePWdn54E7qyS-v8Jl4ZqpI

and I'm using Visual Studio Community 2017 on Windows 10 Pro

Is there anything I have to do to be able to get NetStandard.Library 2.1?

**Comment by vpapenko** [comment]
> Is there anything I have to do to be able to get NetStandard.Library 2.1?
You can fork this repository and downgrade to NetStandart 2.0, but it's better to wait until I add support of both versions. Will add it soon.

**Comment by vpapenko** [comment]
> Is there anything I have to do to be able to get NetStandard.Library 2.1?
You need Net Core 3.0 to use Net Standard 2.1, and it looks like it is not supported for VS 2017.
You can fork this repository and downgrade to NetStandart 2.0, but it's better to wait until I add support of both 2.0 and 2.1 versions. I will add it soon.

**Comment by vpapenko** [comment]
Hi.
ColorPicker is supporting Net Standard 2.0 and 2.1, so you can use it in your project without upgrade to 2.1
