### ISSUE TITLE
Can you please add UWP also to it?

### ISSUE THREAD

**Issue by mwaqash** [vpapenko/ColorPicker#38]
**Is your feature request related to a problem? Please describe.**
Doesn't support UWP

**Describe the solution you'd like**
Please include UWP 

**Describe alternatives you've considered**

**Additional context**
I think it would be very easy to add UWP as skiasharp is fully supported in UWP.

**Comment by vpapenko** [comment]
Hi. Good idea.
I'll start this week

**Comment by vpapenko** [comment]
UWP support is implemented.
New version is available on NuGet.

**Comment by mwaqash** [comment]
Thank you! Great.
