### ISSUE TITLE
UWP app Unable to Generate release build for x64& ARM

### ISSUE THREAD

**Issue by kumaresan-cgvak** [vpapenko/ColorPicker#43]
**Describe the bug**
Unable to generate the release build, when we try to build for Processor architecture x64 & ARM

**To Reproduce**
1. Create a new Xamarin Forms project that supports UWP.
2. Add Color Picker Plugin
3. Try to generate the release build with Processor architecture x64 / ARM

**Expected behavior**
The app should generate UWP release build for x86, x64 & ARM without any issue.

**Screenshots**
<img width="1560" alt="Screenshot 2020-09-15 at 8 16 11 PM" src="https://user-images.githubusercontent.com/5547152/93298964-dfbc1800-f811-11ea-8ec2-4a0d728ba6cc.png">

**Desktop (please complete the following information):**
 - OS: Windows 10  
<img width="420" alt="Screenshot 2020-09-16 at 11 46 09 AM" src="https://user-images.githubusercontent.com/5547152/93299175-44777280-f812-11ea-809f-5ae5cc44e0f5.png">
- Visual Studio Community 2019 (Version 4.8.04084)
- Xamarin Forms 4.7.0.1351

**Comment by kumaresan-cgvak** [comment]
@vpapenko Kindly check this issue and provide your valuable support ASAP.

**Comment by vpapenko** [comment]
New version is available on NuGet.org
It can be built on x86, x64 & ARM and tested on x86, x64.
If you can run and test on ARM device, please confirm that this version is ok.

**Comment by kumaresan-cgvak** [comment]
@vpapenko Thanks for the quick support. Now am able to generate UWp release build for all processor types.(x86, x64 & ARM) Will update you after checking it in the ARM device

**Comment by kumaresan-cgvak** [comment]
@vpapenko In the UWP release build, the Color picker is not working. i.e User Interaction on ShowLuminosityWheel & Color Wheel is not working.

Tried to run the UWP Test App present in Repo with release mode and encountered the same issue.

**Comment by vpapenko** [comment]
@kumaresan-cgvak 
I found a workaround for this problem.
Use the new v1.3.4.11 version and follow instructions in [readme.md](https://github.com/vpapenko/ColorPicker#how-to-use):
Replace
```C#
Xamarin.Forms.Forms.Init(e);
``` 
in ```OnLaunched``` of ```App.xaml.cs``` by
```C#
var rendererAssemblies = ColorPicker.UWP.ColorPickerEffects.GetRendererAssemblies();
Xamarin.Forms.Forms.Init(e, rendererAssemblies);
```
